language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+android-card-form@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
script: ./gradlew clean lint test
after_success: ./deploy_snapshot.sh